### ISSUE TITLE
help error

### ISSUE THREAD

**Issue by dudimarcus** [UCLOrengoGroup/cath-tools-seqscan#1]
perl ./script/cath-tools-seqscan.pl --usage
Can't locate Text/LineFold.pm in @INC (you may need to install the Text::LineFold module) (@INC contains: /Users/marcus/Tools/cath-tools-seqscan-master/script/../extlib/lib/perl5 /Users/marcus/Tools/cath-tools-seqscan-master/script/../lib /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/marcus/Tools/cath-tools-seqscan-master/script/../extlib/lib/perl5/MooX/Options/Descriptive/Usage.pm line 147.

**Comment by sillitoe** [comment]
Not sure why this external dependency didn't get saved along with everything else.

Added `Text::LineFold` module to `./extlib` in cd4e8c06f9af2f745ff6d0908b7b953b53aec5c1

Could you try again?

**Comment by dudimarcus** [comment]
Still the same errors...

cath-tools-seqscan marcus$ perl ./script/cath-tools-seqscan.pl --help
Can't locate Text/LineFold.pm in @INC (you may need to install the Text::LineFold module) (@INC contains: /Users/marcus/Tools/cath-tools-seqscan/script/../extlib/lib/perl5 /Users/marcus/Tools/cath-tools-seqscan/script/../lib /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/marcus/Tools/cath-tools-seqscan/script/../extlib/lib/perl5/MooX/Options/Descriptive/Usage.pm line 147.

cath-tools-seqscan marcus$ perl ./script/cath-tools-seqscan.pl --usage
Can't locate Text/LineFold.pm in @INC (you may need to install the Text::LineFold module) (@INC contains: /Users/marcus/Tools/cath-tools-seqscan/script/../extlib/lib/perl5 /Users/marcus/Tools/cath-tools-seqscan/script/../lib /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/marcus/Tools/cath-tools-seqscan/script/../extlib/lib/perl5/MooX/Options/Descriptive/Usage.pm line 147.

cath-tools-seqscan marcus$ perl ./script/cath-tools-seqscan.pl --man
Can't locate Text/LineFold.pm in @INC (you may need to install the Text::LineFold module) (@INC contains: /Users/marcus/Tools/cath-tools-seqscan/script/../extlib/lib/perl5 /Users/marcus/Tools/cath-tools-seqscan/script/../lib /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/marcus/Tools/cath-tools-seqscan/script/../extlib/lib/perl5/MooX/Options/Descriptive/Usage.pm line 147.

**Comment by sillitoe** [comment]
Okay, thank - this isn't the code - it's an issue with dependencies - your version of Perl can't see the Text::LineFold module. 

Usually you would let Perl install dependencies for itself but I tried to avoid the hassle of installing libraries by including the dependencies in this repo.

Unfortunately the version of Perl you are using on your Mac is compiled differently to mine (`darwin-thread-multi-2level` vs `darwin-2level`) so the external libraries I included in this repo aren't being seen. Never mind.

Probably easiest to install the tool `cpanm`:

http://stackoverflow.com/questions/2980297/how-can-i-use-cpan-as-a-non-root-user

Then you can install the dependencies so they work on your machine by:

```
cd cath-tools-seqscan
cpanm -L extlib --reinstall --installdeps .
```

**Comment by sillitoe** [comment]
Please submit a pull request that includes any files that get installed on your machine

e.g.

```
./extlib/lib/perl5/darwin-thread-multi-2level/Text/LineFold.pm
```

**Comment by sillitoe** [comment]
You got this to work? In Japan at the moment, probably going to crash soon...

**Comment by dudimarcus** [comment]
Works! there are problems with our local mirrors and the modules were not installed, changed cpan to a different mirror and now it works, thanks Ian!

**Comment by sillitoe** [comment]
Great news.

It would be great if you can add any files that got installed to git and
submit a PR so I can avoid this happening to anyone else.

Ta

**Comment by dudimarcus** [comment]
Not sure what to do with the PR as they are currently identical

**Comment by sillitoe** [comment]
No problem - I'll close.

Probably a better bet to let people install the dependencies for themselves anyway
