### ISSUE TITLE
Getting full list of families alignments

### ISSUE THREAD

**Issue by dudimarcus** [UCLOrengoGroup/cath-tools-seqscan#2]
Running the script gives many families hits, but alignments are only written for the top family, any chance this could be controlled or added to retrieve the full list of alignments?

**Comment by sillitoe** [comment]
Feature added in 9e7d766499315e6b302436c91c388df7ef7285e1

NB: note the new usage

**Comment by dudimarcus** [comment]
Thanks! in cases the folder does not exist throws this error:

Output directory does not exist - attempting to create...Can't locate object method "mktree" via package "Path::Class::Dir" at /Users/marcus/Tools/cath-tools-seqscan/script/../lib/Cath/Tools/Seqscan.pm line 78.

same problem as before?

**Comment by sillitoe** [comment]
thanks - typo

**Comment by dudimarcus** [comment]
thanks!
