### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dudimarcus** [UCLOrengoGroup/cath-tools-seqscan#6]
The sequence below gave the following error:

> query
> ADVFHLGLTKAMLDGATLAIVPGDPERVKRIAELMDNATFLASHREYTSYLAYADGKPVVICSTGIGGPSTSIAVEELAQ
> LGVNTFLRVGTTGAIQPHVNVGDVIVTQASVRLDGASLHFAPMEFPAVANFECTTAMVAACRDAGVEPHIGVTASSDTFY
> PGQERYDTVTGRVTRRFAGSMKEWQDMGVLNYEMESATLFTMCATQGWRAACVAGVIVNRTQQEIPDEATMVSAVSIVVA
> AAKKLLA

Setting host to http://beta.cathdb.info/
Submitting sequence...
POST   /search/by_funfhmmer                                                   202
Sequence submitted... got task id: de649055d6545dd54d0dc7203b2406b4
GET    /search/by_funfhmmer/check/de649055d6545dd54d0dc7203b2406b4            200
status: running
GET    /search/by_funfhmmer/check/de649055d6545dd54d0dc7203b2406b4            200
status: running
GET    /search/by_funfhmmer/check/de649055d6545dd54d0dc7203b2406b4            200
status: running
GET    /search/by_funfhmmer/check/de649055d6545dd54d0dc7203b2406b4            200
status: running
GET    /search/by_funfhmmer/check/de649055d6545dd54d0dc7203b2406b4            200
status: done
Retrieving scan results for task id: de649055d6545dd54d0dc7203b2406b4
GET    /search/by_funfhmmer/results/de649055d6545dd54d0dc7203b2406b4?max_hits=50 200
HIT  3.40.50.1580/FF/5979           9.6e-138 Uridine phosphorylase
HIT  3.40.50.1580/FF/2436           1.2e-43 Uridine phosphorylase
HIT  3.40.50.1580/FF/4594           1.7e-34 Phosphorylase superfamily protein
HIT  3.40.50.1580/FF/6092           2.7e-30 Purine nucleoside phosphorylase DeoD-type
HIT  3.40.50.1580/FF/4309           4.6e-30 Purine or other phosphorylase family 1
HIT  3.40.50.1580/FF/3469           2.1e-23 Uridine phosphorylase
HIT  3.40.50.1580/FF/6091           1.6e-15 Uridine phosphorylase 1, isoform CRA_a
HIT  3.40.50.1580/FF/2937           5.2e-10 Uridine phosphorylase
HIT  3.40.50.1580/FF/6120           2.9e-07 MTA/SAH nucleosidase
HIT  3.40.50.1580/FF/5988           1.8e-04 Putative AMP nucleosidase
Retrieving alignment [1] 3.40.50.1580/FF/5979 ...
POST   /search/by_sequence/align_hit                                          200
! Error: id '1rxsj00' does not look like a CATH domain id at cath-tools-seqscan-master/script/../lib/Cath/Tools/Seqscan.pm line 210.
    Cath::Tools::Seqscan::get_domain_lookup_from_alignment('IO::String=GLOB(0x7f8243b51ce8)') called at cath-tools-seqscan-master/script/../lib/Cath/Tools/Seqscan.pm line 157
    Cath::Tools::Seqscan::run('Cath::Tools::Seqscan=HASH(0x7f8243a1c0c0)') called at ../cath-tools-seqscan-master/script/cath-tools-seqscan.pl line 13

**Comment by sillitoe** [comment]
Thanks.

I was being too strict expecting only uppercase chain codes.

I've added a test to cover:

```
prove -l t/gh_006.t
```

I'll let you close the ticket if you're happy

**Comment by dudimarcus** [comment]
Great! works now.

**Comment by dudimarcus** [comment]
Something might have changed in the server as the error is back now:

Setting host to http://beta.cathdb.info/
Submitting sequence...
POST   /search/by_funfhmmer                                                   202
Sequence submitted... got task id: d1ae65fae5b1cdda25d6e3687f56bd66
GET    /search/by_funfhmmer/check/d1ae65fae5b1cdda25d6e3687f56bd66            200
status: done
Retrieving scan results for task id: d1ae65fae5b1cdda25d6e3687f56bd66
GET    /search/by_funfhmmer/results/d1ae65fae5b1cdda25d6e3687f56bd66?max_hits=5 200
HIT  1.10.565.10/FF/338             4.5e-195 Estrogen receptor alpha variant U1
HIT  1.10.565.10/FF/1898            9.4e-153 Estrogen receptor
HIT  1.10.565.10/FF/5096            7.7e-115 Estrogen receptor beta 1
HIT  3.30.50.10/FF/4124             6.5e-39 Estrogen receptor beta 4
HIT  1.10.565.10/FF/5028            3.9e-30 Retinoic acid receptor RXR-beta
Retrieving alignment [1] 1.10.565.10/FF/338 ...
POST   /search/by_sequence/align_hit                                          200
! Error: id '1ereE00 ' does not look like a CATH domain id at cath/cath-tools-seqscan-master/script/../lib/Cath/Tools/Seqscan.pm line 220.
    Cath::Tools::Seqscan::get_domain_lookup_from_alignment('IO::String=GLOB(0x7ffe9902cfe0)') called at cath/cath-tools-seqscan-master/script/../lib/Cath/Tools/Seqscan.pm line 165
    Cath::Tools::Seqscan::run('Cath::Tools::Seqscan=HASH(0x7ffe97796ac0)') called at ../cath-tools-seqscan-master/script/cath-tools-seqscan.pl line 13

**Comment by sillitoe** [comment]
This is me fixing #7 - 2 secs

**Comment by sillitoe** [comment]
Made some changes to the backend server to accomodate #7 

3f6f2114f4493078903bc6104a45498edb65138d allows this code to work with those changes
