### ISSUE TITLE
Biomap sequences

### ISSUE THREAD

**Issue by dudimarcus** [UCLOrengoGroup/cath-tools-seqscan#7]
Hi Ian, is there a way to decipher the heading for the biomap sequences results? 
I understand they might be uniprot sequences but there is only a long hash key in the header.

for example:

> query/1-235
> slalsltaDQMVSALLDAEPPILYSE------FSEASMMGLLTNLADRELVHMINWAKRV
> PGFVDLTLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEI
> FDMLLATSSRFRMMNLQGEEFVCLKSIILLNSGVYTF---TLKSLEEKDHIHRVLDKITD
> TLIHLMAKAGLTLQQQHQRLAQLLLILSHIRHMSNKGMEHLYSMKCKNVVPLYDLLLEML
> DAHR---
> biomap|4.1.0|48b22b698179926749cc88efdcd1cd83/67-305
> ........DQMVSALLEAEPPVVYSEYDPSRPFNEASVMTLLTNLADRELVHMINWAKRV
> PGFVDLALHDQVHLLECAWLEILMVGLVWRSMEHPGKLLFAPNLLLDRSHGKVVEGFVEI
> FDMLLAASSRFRMMNVRGEEFVCLKSIILLNPGIYTYLSSTLKSVEERDHIHRVLDKITD
> TLMHLMAKSGLSLQQQHRRLAQLLLILSHIRHMSNKGMEHLYSMKCKNVVPLYDLLLEML
> DAHRLHA

**Comment by sillitoe** [comment]
I'll add in some meta tags in the description for each sequence header - if we can map the sequence domain to a UniProtKB accession then it will appear in the headers.

Worth noting that there is not a one-to-one relationship between sequence domain id (`$md5/$start-$stop`) and UniProtKB accession - each sequence domain id can have 0, 1 or more UniProtKB accessions.

Each entry corresponds to a predicted structural domain (i.e. region) of a unique protein sequence in Gene3D. Some of these ids will map to a protein sequence in UniProtKB. Some of them will map to protein sequences from Ensembl. Some of them may map to more than one UniProtKB entry (e.g. two proteins with the same sequence coming from different organisms).

**Comment by dudimarcus** [comment]
Many thanks!

If there’s an easy way to add ids including those from Ensembl it would be great!

**Comment by sillitoe** [comment]
Should be solved by 0ad762567b7e08b503dc3d30d20144c75348aae1

Resulting alignments have:

 * sequences automatically mapped to UniProtKB accessions
 * CATH Domain sequences use correct numbering in the sequence header (based on SEQRES)
 * mapping between SEQRES and ATOM records in meta data
 * stockholm format also provides additional data: DOPS score, SCORECONS, etc
