### ISSUE TITLE
Bugs in the new version

### ISSUE THREAD

**Issue by dudimarcus** [UCLOrengoGroup/cath-tools-seqscan#8]
Some minor changes but might worth mentioning.

In the alignments results files some things have changed:
- fasta are now one liner instead of 80 char limit (no big issue)
- title for the query first instance in each file changed (now without start-end)
- some alignment are not matching the query with variable lengths

for example two lines from the same file are not in the same length:

> biomap|4.1.0|44065ac602ae7ac62af1debdc451ff77 
> ......................acrlrkcyevgmmkggirkdrrggrmlkhkrqrddgegrgevgSagdmraa.......nlwpsplmIKRSKKNSLALSLTADQMVSALLDAEPPILYSEYDPTRPFSEASMMGLLTNLADRELVHMINWAKRVPGFVDLTLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLN...SGI--------------------------------------------------------SHVEAKK--------------------RILNLHP-.....
> cath|4.1.0|2ertA00/1-261 
> ..............................................................mdpM......................IKRSKKNSLALSLTADQMVSALLDAEPPILYSEYDPTRPFSEASMMGLLTNLADRELVHMINWAKRVPGFVDLTLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLN...SGVYTFLSSTLK

**Comment by sillitoe** [comment]
Can you provide the query sequence that returned this alignment?

**Comment by dudimarcus** [comment]
I think it was this one:

```
>p03372
MTMTLHTKASGMALLHQIQGNELEPLNRPQLKIPLERPLGEVYLDSSKPAVYNYPEGAAYEFNAAAAANAQVYGQTGLPY
GPGSEAAAFGSNGLGGFPPLNSVSPSPLMLLHPPPQLSPFLQPHGQQVPYYLENEPSGYTVREAGPPAFYRPNSDNRRQG
GRERLASTNDKGSMAMESAKETRYCAVCNDYASGYHYGVWSCEGCKAFFKRSIQGHNDYMCPATNQCTIDKNRRKSCQAC
RLRKCYEVGMMKGGIRKDRRGGRMLKHKRQRDDGEGRGEVGSAGDMRAANLWPSPLMIKRSKKNSLALSLTADQMVSALL
DAEPPILYSEYDPTRPFSEASMMGLLTNLADRELVHMINWAKRVPGFVDLTLHDQVHLLECAWLEILMIGLVWRSMEHPG
KLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLNSGVYTFLSSTLKSLEEKDHIHRVLD
KITDTLIHLMAKAGLTLQQQHQRLAQLLLILSHIRHMSNKGMEHLYSMKCKNVVPLYDLLLEMLDAHRLHAPTSRGGASV
EETDQSHLATAGSTSSHSLQKYYITGEAEGFPATV
```

**Comment by sillitoe** [comment]
Looks like this was affecting the last sequence in the alignment.

Result of the server sending the file before closing (and flushing) the file handle.

Applied fix at the backend and added test to confirm.
