### ISSUE TITLE
Misalignment of start-stop

### ISSUE THREAD

**Issue by dudimarcus** [UCLOrengoGroup/cath-tools-seqscan#9]
Hi, I noticed that when the sequence starts above >1 there is always misalignment to the pdb SEQRES which means the fix for start-stop could be not calibrated.

for example:

good:
correctly starts in 1

> cath|4.1.0|1a52A00/1-258 
> .................................................................-.....................mIKRSKKNSLALSLTADQMVSALLDAEPPILYSEYDPTRPFSEASMMGLLTNLADRELVHMINWAKRVPGFVDLTLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLN...SGVYTFLSSTLKSLEEKDHIHRVLDKITDTLIHLMAKAGLTLQQQHERLAQLLLILSHIRHMSNKGMEHLYSMKCKNVVPLYDLLLEMLDAHRLhapts

bad:
should actually started in 24 not 8

> cath|4.1.0|2jfaA00/8-252 
> .................................................................-......................-------SLALSLTADQMVSALLDAEPPILYSEYDPTRPFSEASMMGLLTNLADRELVHMINWAKRVPGFVDLTLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLN...SGVYTFLSSTLKSLEEKDHIHRVLDKITDTLIHLMAKAGLTLQQQHQRLAQLLLILSHIRHMSNKGMEHLYSMKCKNV----------------.....

**Comment by sillitoe** [comment]
Working on this now...

**Comment by dudimarcus** [comment]
Great! thanks Ian

**Comment by sillitoe** [comment]
Okay. Progress.
- I've reverse engineered the logic behind the code that was responsible for generating these expanded domain sequence boundaries
- I've added a ton of sanity checks to make sure the sequence boundaries match the sequence files used in the FunFams
- I'm currently generating the updated lookup file - looks like it will take around an hour

Should be finished by the time I get home - I'll commit the new lookup file and all should work correctly.

**Comment by dudimarcus** [comment]
That's great! thanks Ian.
Looking forward to testing it tomorrow, previous version already showed great results.

**Comment by sillitoe** [comment]
Okay, this should be fixed now.

As a summary:
- the [domain boundaries](../blob/master/data/domain-sequence-numbering.v4_1_0.txt) have been recalculated
- the new sequences and boundaries have been checked against the raw data files to guarantee that the lengths and sequences match
- added a test to check for the specific case above

Can you confirm this works and close the ticket if you're happy.

**Comment by dudimarcus** [comment]
Yay, its fixed, all misalignment examples are corrected now.

Thanks Ian!

**Comment by sillitoe** [comment]
Great.

For the record - there were 4 domains (of 383,628) where the domain boundaries of our internal files do not match the results of the original algorithm that was used to generate them.

I'm not yet sure how this happened, but just to let you know that if you happen to hit these domain ids (they are all identical sequences) then the script will throw an exception.

```
$ grep 'Error' data/domain-sequence-numbering.v4_1_0.txt
# Error: 4ikpA01 has mismatching domain boundaries
# Error: 4ikpB01 has mismatching domain boundaries
# Error: 4ikpC01 has mismatching domain boundaries
# Error: 4ikpD01 has mismatching domain boundaries
```
